Создание тензора

In [1]:
import torch
import math

In [2]:
x = torch.empty(3,4)
print(type(x))
print(x)

<class 'torch.Tensor'>
tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])


In [3]:
zero  = torch.zeros(2,3)
zero

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [4]:
one  = torch.ones(2,3)
one

tensor([[1., 1., 1.],
        [1., 1., 1.]])

In [5]:
torch.manual_seed(1729)
rand = torch.rand(2,3)
rand

tensor([[0.3126, 0.3791, 0.3087],
        [0.0736, 0.4216, 0.0691]])

In [6]:
rand1 = torch.rand(2,3)
rand1

tensor([[0.2332, 0.4047, 0.2162],
        [0.9927, 0.4128, 0.5938]])

In [23]:
x1 = torch.empty(2,4,3)
print(x.shape)
x1

torch.Size([2, 2, 3])


tensor([[[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]]])

In [10]:
empty_like_x = torch.empty_like(x1)
print(empty_like_x.shape)
print(empty_like_x)

torch.Size([2, 2, 3])
tensor([[[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]]])


In [11]:
a = torch.ones((2,3), dtype=torch.int16)
a

tensor([[1, 1, 1],
        [1, 1, 1]], dtype=torch.int16)

In [12]:
b = torch.rand((2,3), dtype=torch.float64)*20
b

tensor([[18.0429,  7.2532, 19.6519],
        [10.8626,  2.1505, 19.6913]], dtype=torch.float64)

In [13]:
c  = b.to(torch.int32)
c

tensor([[18,  7, 19],
        [10,  2, 19]], dtype=torch.int32)

Базовая арифметика со скалярами

In [27]:
ones = torch.ones(2,2) + 2
ones

tensor([[3., 3.],
        [3., 3.]])

In [17]:
twos = torch.ones(2,2)*3
twos

tensor([[3., 3.],
        [3., 3.]])

In [19]:
threes = (torch.ones(2,2)*9-1)/2
threes

tensor([[4., 4.],
        [4., 4.]])

In [20]:
fours = twos*2
fours

tensor([[6., 6.],
        [6., 6.]])

In [21]:
sqrt2s = twos**0.5
sqrt2s

tensor([[1.7321, 1.7321],
        [1.7321, 1.7321]])

Арифметические операции с двумя тензорами

In [26]:
powers2 = ones ** torch.tensor([[1,2], [3,4]])
powers2

tensor([[ 3.,  9.],
        [27., 81.]])

In [28]:
fives = ones+fours
fives

tensor([[9., 9.],
        [9., 9.]])

In [29]:
dozens = threes*fours
dozens

tensor([[24., 24.],
        [24., 24.]])

In [32]:
a = torch.rand(2,3)
b = torch.rand(3,2)

print(a*b)# будет ошибка так как тензоры разных размерностей

RuntimeError: The size of tensor a (3) must match the size of tensor b (2) at non-singleton dimension 1