# Тема “Вычисления с помощью Numpy”


## Задание 1
Импортируйте библиотеку Numpy и дайте ей псевдоним np.
Создайте массив Numpy под названием a размером 5x2, то есть состоящий из 5 строк и 2 столбцов. Первый столбец должен содержать числа 1, 2, 3, 3, 1, а второй - числа 6, 8, 11, 10, 7. Будем считать, что каждый столбец - это признак, а строка - наблюдение. Затем найдите среднее значение по каждому признаку, используя метод mean массива Numpy. Результат запишите в массив mean_a, в нем должно быть 2 элемента.

In [1]:
import numpy as np

In [18]:
quantity_sing = 2
quantity_observ = 5

In [2]:
a  = np.array([[1,6],
               [2,8],
               [3,11],
               [3,10],
               [1,7]])
a

array([[ 1,  6],
       [ 2,  8],
       [ 3, 11],
       [ 3, 10],
       [ 1,  7]])

In [12]:
mean_sing_1 = a[:,0].mean()
mean_sing_2 = a[:,1].mean()
mean_a = np.array([mean_sing_1,mean_sing_2])
mean_a


array([2. , 8.4])

In [10]:
type(mean_a)

numpy.ndarray

## Задание 2
Вычислите массив a_centered, отняв от значений массива “а” средние значения соответствующих признаков, содержащиеся в массиве mean_a. Вычисление должно производиться в одно действие. Получившийся массив должен иметь размер 5x2.


In [8]:
a_centered = a - mean_a
a_centered

array([[-1. , -2.4],
       [ 0. , -0.4],
       [ 1. ,  2.6],
       [ 1. ,  1.6],
       [-1. , -1.4]])

In [9]:
type(a_centered)

numpy.ndarray

## Задание 3
Найдите скалярное произведение столбцов массива a_centered. В результате должна получиться величина a_centered_sp. Затем поделите a_centered_sp на N-1, где N - число наблюдений.


In [19]:
a_centered_sp = np.dot(a_centered[:,0],a_centered[:,1])
cov = a_centered_sp/quantity_observ
cov

np.float64(1.6)

In [1]:
!pip install ipython-git

ERROR: Could not find a version that satisfies the requirement ipython-git (from versions: none)
ERROR: No matching distribution found for ipython-git


In [2]:
!git status

On branch main
Your branch is up to date with 'origin/main'.

Changes not staged for commit:
  (use "git add <file>..." to update what will be committed)
  (use "git restore <file>..." to discard changes in working directory)
	modified:   hw_numpy.ipynb

Untracked files:
  (use "git add <file>..." to include in what will be committed)
	../pandas/book_info.pkl

no changes added to commit (use "git add" and/or "git commit -a")


In [3]:
!git add hw_numpy.ipynb

In [4]:
!git commit -m "Update: completed numpy exercises"

[main 3a79b83] Update: completed numpy exercises
 1 file changed, 57 insertions(+)


In [5]:
!git push origin main

To https://github.com/KorbovskiyOleg/DataScience.git
   ad44d32..3a79b83  main -> main


In [1]:
!pip install jupyterlab-git

   ---------------------------------------- 0.0/5.9 MB ? eta -:--:--
   ---------------------------------------- 0.0/5.9 MB ? eta -:--:--
   - -------------------------------------- 0.3/5.9 MB ? eta -:--:--
   - -------------------------------------- 0.3/5.9 MB ? eta -:--:--
   - -------------------------------------- 0.3/5.9 MB ? eta -:--:--
   - -------------------------------------- 0.3/5.9 MB ? eta -:--:--
   - -------------------------------------- 0.3/5.9 MB ? eta -:--:--
   --- ------------------------------------ 0.5/5.9 MB 234.0 kB/s eta 0:00:24
   ----- ---------------------------------- 0.8/5.9 MB 374.3 kB/s eta 0:00:14
   -------- ------------------------------- 1.3/5.9 MB 676.3 kB/s eta 0:00:07
   ---------- ----------------------------- 1.6/5.9 MB 748.6 kB/s eta 0:00:06
   ---------- ----------------------------- 1.6/5.9 MB 748.6 kB/s eta 0:00:06
   ---------- ----------------------------- 1.6/5.9 MB 748.6 kB/s eta 0:00:06
   ---------- ----------------------------- 1.6/5

In [2]:
!pip install --upgrade jupyterlab-git

In [3]:
!jupyter server extension enable --py jupyterlab_git

Extension package aext_assistant took 1.6520s to import
****************** ENVIRONMENT [Panels] Environment.PRODUCTION ******************
****************** ENVIRONMENT [Panels] Environment.PRODUCTION ******************
Database not initialized by migration_upgrade(). Running it again
Database not initialized by migration_upgrade(). Running it again
--> Alembic Config: {'db_conn_url': 'sqlite:///C:\\Users\\Админ\\Desktop\\py\\DataScince\\homework_1\\numpy\\anaconda_projects\\db\\project_filebrowser.db', 'db_path': 'C:\\Users\\Админ\\Desktop\\py\\DataScince\\homework_1\\numpy\\anaconda_projects\\db\\project_filebrowser.db'}
Default dir: C:\Users\Админ\Desktop\py\DataScince\homework_1\numpy. Running chdir...
Checking for database file @ C:\Users\Админ\Desktop\py\DataScince\homework_1\numpy\anaconda_projects\db\project_filebrowser.db
Creating database file...
Migrations executed
--> Alembic Config: {'db_conn_url': 'sqlite:///C:\\Users\\Админ\\Desktop\\py\\DataScince\\homework_1\\numpy\\an

In [4]:
!jupyter server extension list

Config dir: C:\Users\Админ\.jupyter
Config dir: C:\DataScience\etc\jupyter
    aext_assistant enabled
    - Validating aext_assistant...
      aext_assistant 4.20.0 ok
    aext_core enabled
    - Validating aext_core...
      aext_core 4.20.0 ok
    aext_panels enabled
    - Validating aext_panels...
      aext_panels 4.20.0 ok
    aext_share_notebook enabled
    - Validating aext_share_notebook...
      aext_share_notebook 4.20.0 ok
    aext_toolbox enabled
    - Validating aext_toolbox...
      aext_toolbox 4.20.0 ok
    jupyter_lsp enabled
    - Validating jupyter_lsp...
      jupyter_lsp 2.2.5 ok
    jupyter_server_mathjax enabled
    - Validating jupyter_server_mathjax...
      jupyter_server_mathjax  ok
    jupyter_server_terminals enabled
    - Validating jupyter_server_terminals...
      jupyter_server_terminals 0.5.3 ok
    jupyterlab enabled
    - Validating jupyterlab...
      jupyterlab 4.3.4 ok
    jupyterlab_git enabled
    - Validating jupyterlab_git...
      jupyterlab_


Extension package aext_assistant took 1.6482s to import
****************** ENVIRONMENT [Panels] Environment.PRODUCTION ******************
****************** ENVIRONMENT [Panels] Environment.PRODUCTION ******************
--> Alembic Config: {'db_conn_url': 'sqlite:///C:\\Users\\Админ\\Desktop\\py\\DataScince\\homework_1\\numpy\\anaconda_projects\\db\\project_filebrowser.db', 'db_path': 'C:\\Users\\Админ\\Desktop\\py\\DataScince\\homework_1\\numpy\\anaconda_projects\\db\\project_filebrowser.db'}
Default dir: C:\Users\Админ\Desktop\py\DataScince\homework_1\numpy. Running chdir...
Checking for database file @ C:\Users\Админ\Desktop\py\DataScince\homework_1\numpy\anaconda_projects\db\project_filebrowser.db
Database file already exists
Migrations executed
Checking project configuration: C:\Users\Админ\Desktop\py\DataScince\homework_1\numpy. Running chdir...
Initializing a new watchdog thread: []
Successfully initialized a watchdog thread: [15312]
Extension package aext_toolbox took 0.3929s 