# Тема “Вычисления с помощью Numpy”


## Задание 1
Импортируйте библиотеку Numpy и дайте ей псевдоним np.
Создайте массив Numpy под названием a размером 5x2, то есть состоящий из 5 строк и 2 столбцов. Первый столбец должен содержать числа 1, 2, 3, 3, 1, а второй - числа 6, 8, 11, 10, 7. Будем считать, что каждый столбец - это признак, а строка - наблюдение. Затем найдите среднее значение по каждому признаку, используя метод mean массива Numpy. Результат запишите в массив mean_a, в нем должно быть 2 элемента.

In [1]:
import numpy as np

In [18]:
quantity_sing = 2
quantity_observ = 5

In [2]:
a  = np.array([[1,6],
               [2,8],
               [3,11],
               [3,10],
               [1,7]])
a

array([[ 1,  6],
       [ 2,  8],
       [ 3, 11],
       [ 3, 10],
       [ 1,  7]])

In [12]:
mean_sing_1 = a[:,0].mean()
mean_sing_2 = a[:,1].mean()
mean_a = np.array([mean_sing_1,mean_sing_2])
mean_a


array([2. , 8.4])

In [10]:
type(mean_a)

numpy.ndarray

## Задание 2
Вычислите массив a_centered, отняв от значений массива “а” средние значения соответствующих признаков, содержащиеся в массиве mean_a. Вычисление должно производиться в одно действие. Получившийся массив должен иметь размер 5x2.


In [8]:
a_centered = a - mean_a
a_centered

array([[-1. , -2.4],
       [ 0. , -0.4],
       [ 1. ,  2.6],
       [ 1. ,  1.6],
       [-1. , -1.4]])

In [9]:
type(a_centered)

numpy.ndarray

## Задание 3
Найдите скалярное произведение столбцов массива a_centered. В результате должна получиться величина a_centered_sp. Затем поделите a_centered_sp на N-1, где N - число наблюдений.


In [19]:
a_centered_sp = np.dot(a_centered[:,0],a_centered[:,1])
cov = a_centered_sp/quantity_observ
cov

np.float64(1.6)

In [1]:
!pip install ipython-git

ERROR: Could not find a version that satisfies the requirement ipython-git (from versions: none)
ERROR: No matching distribution found for ipython-git


In [2]:
!git status

On branch main
Your branch is up to date with 'origin/main'.

Changes not staged for commit:
  (use "git add <file>..." to update what will be committed)
  (use "git restore <file>..." to discard changes in working directory)
	modified:   hw_numpy.ipynb

Untracked files:
  (use "git add <file>..." to include in what will be committed)
	../pandas/book_info.pkl

no changes added to commit (use "git add" and/or "git commit -a")
